name: flutter_application_1
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^0.13.5
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  firebase_core: ^1.22.0
  firebase_auth: ^3.8.0
  fluttertoast: ^8.0.9
  flutter_switch: ^0.3.2
  onboarding: ^3.1.0
  path: ^1.8.0
  firebase_storage: ^10.3.8
  permission_handler: ^10.0.0
  image_picker: ^0.8.5+3
  flutter_auth: ^0.0.1
  flutter_login_facebook: ^1.6.0
  google_sign_in: ^5.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/python.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
